### ISSUE TITLE
Confusion about CrossNorm and GlobalNorm

### ISSUE THREAD

**Issue by lif314** [Aiolus-X/Norm-INR#2]
The current experimental results only report the results of the training phase (PSNR), but due to the difference in the modes of batch_dim and feature_dim, CrossNorm and GlobalNorm have poor effects during the evaluation process. Is it the right way to only report the results of the training phase? If the effect is not good during the evaluation process, it means that the images in the stored network weights will not get the results of the training when they are loaded again ? 😭  I am not sure about this doubt. 
My Exp:
```
Training PSNR: 21.50, Eval PSNR: 7.68 
```

**Comment by Aiolus-X** [comment]
Sorry for the late reply. It seems like the issue of quantization. Reloading the weights should not lead to the performance drop.
